
import { supabase, uploadFile } from './supabaseClient';
import { CommunityNote } from '../types';
import { fetchCommunityNotes } from './resourceService';

/**
 * DEVELOPER NOTE: SQL FOR SUPABASE
 * To enable this feature, run the following SQL in your Supabase SQL Editor:
 * 
 * CREATE TABLE community_notes (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   created_at TIMESTAMPTZ DEFAULT NOW(),
 *   title TEXT NOT NULL,
 *   author TEXT,
 *   avatar TEXT,
 *   summary TEXT,
 *   file_type TEXT,
 *   file_size TEXT,
 *   downloads INTEGER DEFAULT 0,
 *   likes INTEGER DEFAULT 0,
 *   category TEXT,
 *   tags TEXT[],
 *   storage_path TEXT
 * );
 * 
 * -- Enable public access (for demo purposes)
 * ALTER TABLE community_notes ENABLE ROW LEVEL SECURITY;
 * CREATE POLICY "Public Access" ON community_notes FOR ALL USING (true) WITH CHECK (true);
 */

/**
 * Fetch all notes from Supabase community_notes table.
 * If the table is missing, gracefully falls back to mock data from resourceService.
 */
export const fetchDBCommunityNotes = async (): Promise<CommunityNote[]> => {
    try {
        const { data, error } = await supabase
            .from('community_notes')
            .select('*')
            .order('created_at', { ascending: false });
        
        if (error) {
            // Check specifically for "table not found" errors
            if (error.message.includes('community_notes') && error.message.includes('not find')) {
                console.warn("Supabase table 'community_notes' missing. Falling back to local mock data.");
                return await fetchCommunityNotes();
            }
            
            console.error("Fetch community notes error:", error.message);
            return await fetchCommunityNotes();
        }

        if (!data || data.length === 0) {
            return await fetchCommunityNotes();
        }

        return data.map(item => ({
            id: item.id ? item.id.toString() : Math.random().toString(),
            title: item.title || '未命名资料',
            author: item.author || '匿名考生',
            avatar: item.avatar || `https://api.dicebear.com/7.x/avataaars/svg?seed=${item.id}`,
            summary: item.summary || '',
            fileType: (item.file_type === 'doc' || item.file_type === 'docx' ? 'doc' : 
                      item.file_type === 'xmind' ? 'xmind' : 
                      item.file_type === 'zip' ? 'zip' : 'pdf') as any,
            size: item.file_size || '0MB',
            downloads: item.downloads || 0,
            likes: item.likes || 0,
            uploadDate: item.created_at ? new Date(item.created_at).toLocaleDateString('zh-CN') : '未知日期',
            category: item.category || '综合',
            tags: item.tags || [],
            storagePath: item.storage_path
        }));
    } catch (e: any) {
        console.warn("Critical exception fetching from DB, falling back to mock data:", e.message || e);
        return await fetchCommunityNotes();
    }
};

/**
 * Share a new note with file upload.
 * If the table is missing, this will fail gracefully with an error message.
 */
export const shareNoteToDB = async (
    title: string, 
    category: string, 
    summary: string, 
    file: File
): Promise<CommunityNote | null> => {
    try {
        // 1. Upload file to Storage
        const fileExt = file.name.split('.').pop()?.toLowerCase() || 'bin';
        const fileName = `${Date.now()}_${Math.random().toString(36).substring(7)}.${fileExt}`;
        const storagePath = `user-uploads/${fileName}`;
        
        await uploadFile('exam-pdfs', storagePath, file);

        // 2. Insert metadata into table
        const { data, error } = await supabase
            .from('community_notes')
            .insert([{
                title,
                category,
                summary,
                file_type: fileExt,
                file_size: (file.size / 1024 / 1024).toFixed(2) + 'MB',
                storage_path: storagePath,
                author: '我 (当前用户)',
                tags: ['原创资料', '最新分享']
            }])
            .select()
            .single();

        if (error) {
            if (error.message.includes('not find')) {
                alert("数据库表 'community_notes' 尚未创建，资料已上传但无法保存记录。请联系管理员运行初始化 SQL。");
            }
            console.error("Metadata insertion error:", error.message);
            throw error;
        }

        return {
            id: data.id.toString(),
            title: data.title,
            author: data.author,
            avatar: `https://api.dicebear.com/7.x/avataaars/svg?seed=${data.id}`,
            summary: data.summary,
            fileType: (data.file_type === 'doc' || data.file_type === 'docx' ? 'doc' : 
                      data.file_type === 'xmind' ? 'xmind' : 
                      data.file_type === 'zip' ? 'zip' : 'pdf') as any,
            size: data.file_size,
            downloads: 0,
            likes: 0,
            uploadDate: new Date(data.created_at).toLocaleDateString('zh-CN'),
            category: data.category,
            tags: data.tags,
            storagePath: data.storage_path
        };
    } catch (e: any) {
        console.error("Share note failed:", e.message || e);
        return null;
    }
};

/**
 * Increment like count in DB
 */
export const toggleLikeInDB = async (id: string, currentLikes: number) => {
    try {
        const { error } = await supabase
            .from('community_notes')
            .update({ likes: currentLikes + 1 })
            .eq('id', id);
        
        if (error) {
            console.error("Error updating like count:", error.message);
        }
    } catch (e: any) {
        console.error("Toggle like exception:", e.message || e);
    }
};
